{"level":"info","message":"üîó Connecting to databases...","service":"intelgraph-api","timestamp":"2025-08-14T01:41:17.781Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Neo4j, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:41:20.807Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to PostgreSQL, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:41:22.812Z"}
{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:23.805Z"}
{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:26.860Z"}
{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:29.966Z"}
{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:33.123Z"}
{"level":"info","message":"üîó Connecting to databases...","service":"intelgraph-api","timestamp":"2025-08-14T01:42:43.114Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Neo4j, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:42:43.127Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to PostgreSQL, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:42:43.129Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Neo4j, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:44:43.604Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to PostgreSQL, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:44:45.630Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Redis, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:47:36.948Z"}
{"level":"error","message":"Redis error: Command timed out","service":"intelgraph-api","stack":"Error: Command timed out\n    at Timeout._onTimeout (/Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/ioredis/built/Command.js:192:33)\n    at listOnTimeout (node:internal/timers:608:17)\n    at process.processTimers (node:internal/timers:543:7)","timestamp":"2025-08-14T01:47:36.956Z"}
{"level":"info","message":"üîó Connecting to databases...","service":"intelgraph-api","timestamp":"2025-08-14T01:47:51.196Z"}
{"level":"info","message":"üîó Connecting to databases...","service":"intelgraph-api","timestamp":"2025-08-14T01:49:00.799Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Neo4j, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:49:05.806Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to PostgreSQL, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:49:10.811Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Redis, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:49:15.819Z"}
{"level":"info","message":"üîó Connecting to databases...","service":"intelgraph-api","timestamp":"2025-08-14T01:50:59.471Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Neo4j, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:04.479Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to PostgreSQL, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:09.496Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Redis, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:14.500Z"}
{"level":"info","message":"üîó Connecting to databases...","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.059Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Neo4j, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.071Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to PostgreSQL, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.073Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Redis error: connect ECONNREFUSED 127.0.0.1:6379","port":6379,"service":"intelgraph-api","stack":"Error: connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)","syscall":"connect","timestamp":"2025-08-14T01:51:41.074Z"}
{"level":"warn","message":"‚ö†Ô∏è Failed to connect to Redis, falling back to mock mode:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.074Z"}
{"level":"info","message":"‚úÖ All databases connected","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.074Z"}
{"level":"info","message":"üîß Initializing services...","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.086Z"}
{"level":"info","message":"WebSocket service initialized with War Room Sync","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.087Z"}
{"level":"info","message":"‚úÖ All services initialized","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.100Z"}
{"level":"info","message":"RuleRunner starting, interval=60000ms, threshold=0.85","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.100Z"}
{"level":"warn","message":"Federation routes not mounted:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.174Z"}
{"level":"info","message":"üìù Report routes mounted at /api/reports","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.421Z"}
{"level":"info","message":"üß† ML routes mounted at /api/ml","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.422Z"}
{"level":"warn","message":"External routes not mounted:","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.422Z"}
{"level":"info","message":"üß™ Simulation routes mounted at /api/simulate","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.423Z"}
{"level":"info","message":"üôÇ Sentiment routes mounted at /api/sentiment","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.423Z"}
{"level":"info","message":"üîå WebSocket service initialized and handling connections","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.423Z"}
{"level":"info","message":"‚öîÔ∏è  War Room sync service enabled with <300ms latency target","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.423Z"}
{"level":"info","message":"üöÄ IntelGraph AI Server running on port 4000","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.425Z"}
{"level":"info","message":"üìä GraphQL endpoint: http://localhost:4000/graphql","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.425Z"}
{"level":"info","message":"üîå WebSocket subscriptions enabled","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.425Z"}
{"level":"info","message":"üåç Environment: development","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.425Z"}
{"level":"info","message":"ü§ñ AI features enabled","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.425Z"}
{"level":"info","message":"üõ°Ô∏è  Security features enabled","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.425Z"}
{"level":"info","message":"üìà Real-time updates enabled","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.425Z"}
{"level":"info","message":"NLP Manager initialized and trained","service":"intelgraph-api","timestamp":"2025-08-14T01:51:41.426Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:51:53 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:51:53.815Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:51:58 +0000] \"GET /api/version HTTP/1.1\" 200 119 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:51:58.460Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:52:01 +0000] \"GET /api/healthz HTTP/1.1\" 200 109 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:52:01.841Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:52:05 +0000] \"GET /api/system/stats HTTP/1.1\" 200 334 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:52:05.093Z"}
{"level":"info","message":"GraphQL Operation: undefined","service":"intelgraph-api","timestamp":"2025-08-14T01:52:11.863Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:52:11 +0000] \"POST /graphql HTTP/1.1\" 200 2487 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:52:11.869Z"}
{"level":"info","message":"GraphQL Operation: undefined","service":"intelgraph-api","timestamp":"2025-08-14T01:52:16.000Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:52:16 +0000] \"POST /graphql HTTP/1.1\" 200 2487 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:52:16.001Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:52:41 +0000] \"GET /api/reports HTTP/1.1\" 401 24 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:52:41.472Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:55:42 +0000] \"GET /api/healthz HTTP/1.1\" 200 109 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:55:42.938Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:55:47 +0000] \"GET /api/db/neo4j HTTP/1.1\" 200 15 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:55:47.240Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:55:50 +0000] \"GET /api/db/postgres HTTP/1.1\" 200 15 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:55:50.423Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:55:53 +0000] \"GET /api/db/redis HTTP/1.1\" 200 15 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:55:53.905Z"}
{"level":"info","message":"GraphQL Operation: undefined","service":"intelgraph-api","timestamp":"2025-08-14T01:55:58.281Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:55:58 +0000] \"POST /graphql HTTP/1.1\" 200 495 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:55:58.284Z"}
{"level":"info","message":"GraphQL Operation: undefined","service":"intelgraph-api","timestamp":"2025-08-14T01:56:03.933Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:03 +0000] \"POST /graphql HTTP/1.1\" 200 366 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:03.947Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:07 +0000] \"GET /metrics HTTP/1.1\" 200 - \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:07.377Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:11 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:11.317Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:12 +0000] \"GET /favicon.ico HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:12.715Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:18 +0000] \"GET /api/system/stats HTTP/1.1\" 200 335 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:18.642Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.419Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.422Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.423Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.424Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.424Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.426Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.426Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.427Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.427Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:25 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:25.432Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:56:29 +0000] \"GET /health HTTP/1.1\" 200 726 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T01:56:29.317Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:58:31 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T01:58:31.526Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:01:58:33 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T01:58:33.623Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:02:03:33 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T02:03:33.850Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:02:03:34 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T02:03:34.792Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:02:03:35 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T02:03:35.876Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:02:03:36 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T02:03:36.953Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:02:20:05 +0000] \"HEAD / HTTP/1.1\" 404 30 \"-\" \"curl/8.7.1\"","service":"intelgraph-api","timestamp":"2025-08-14T02:20:05.361Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:02:21:57 +0000] \"GET /graphql HTTP/1.1\" 200 - \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T02:21:57.768Z"}
{"level":"info","message":"::1 - - [14/Aug/2025:02:22:03 +0000] \"GET / HTTP/1.1\" 404 30 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\"","service":"intelgraph-api","timestamp":"2025-08-14T02:22:03.792Z"}
{"level":"info","message":"SIGTERM received, shutting down gracefully","service":"intelgraph-api","timestamp":"2025-08-14T02:38:46.776Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [14/Aug/2025:05:16:29 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-14T05:16:29.281Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T15:56:12.539Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T15:56:12.550Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.558Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.559Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.564Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.567Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:24:36.576Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:24:36.567Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:24:36.575Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:24:36.579Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:25:36.528Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:25:36.539Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:27:28.436Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:27:28.444Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:27:28.524Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:27:28.530Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:27:28.604Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:27:28.611Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:28:51.693Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:28:51.706Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:28:51.799Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:28:51.805Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:30:13.757Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:30:13.764Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:30:13.844Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-14T19:30:13.850Z"}
{"level":"info","message":"PostgreSQL tables created","service":"intelgraph-api","timestamp":"2025-08-15T08:29:26.517Z"}
{"level":"info","message":"‚úÖ Connected to PostgreSQL","service":"intelgraph-api","timestamp":"2025-08-15T08:29:26.519Z"}
{"level":"info","message":"Migration system initialized","service":"intelgraph-api","timestamp":"2025-08-15T08:29:26.794Z"}
{"level":"info","message":"Found 2 pending migrations","service":"intelgraph-api","timestamp":"2025-08-15T08:29:26.801Z"}
{"level":"info","message":"Running migration 001_initial_entity_model...","service":"intelgraph-api","timestamp":"2025-08-15T08:29:26.802Z"}
{"level":"error","message":"‚ùå Migration 001_initial_entity_model failed:","service":"intelgraph-api","timestamp":"2025-08-15T08:29:34.102Z"}
{"level":"warn","message":"Migration system not available, falling back to legacy constraints","service":"intelgraph-api","timestamp":"2025-08-15T08:29:34.104Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:08:29:36 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T08:29:36.035Z"}
{"level":"info","message":"Neo4j connection closed","service":"intelgraph-api","timestamp":"2025-08-15T08:29:41.286Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T08:29:41.290Z"}
{"level":"info","message":"PostgreSQL tables created","service":"intelgraph-api","timestamp":"2025-08-15T08:33:42.286Z"}
{"level":"info","message":"‚úÖ Connected to PostgreSQL","service":"intelgraph-api","timestamp":"2025-08-15T08:33:42.293Z"}
{"level":"info","message":"Migration system initialized","service":"intelgraph-api","timestamp":"2025-08-15T08:33:42.557Z"}
{"level":"info","message":"Found 2 pending migrations","service":"intelgraph-api","timestamp":"2025-08-15T08:33:42.570Z"}
{"level":"info","message":"Running migration 001_initial_entity_model...","service":"intelgraph-api","timestamp":"2025-08-15T08:33:42.571Z"}
{"level":"error","message":"‚ùå Migration 001_initial_entity_model failed:","service":"intelgraph-api","timestamp":"2025-08-15T08:33:43.363Z"}
{"level":"warn","message":"Migration system not available, falling back to legacy constraints","service":"intelgraph-api","timestamp":"2025-08-15T08:33:43.363Z"}
{"level":"info","message":"Neo4j constraints and indexes created","service":"intelgraph-api","timestamp":"2025-08-15T08:33:43.611Z"}
{"level":"info","message":"‚úÖ Connected to Neo4j","service":"intelgraph-api","timestamp":"2025-08-15T08:33:43.612Z"}
{"level":"info","message":"Migration system initialized","service":"intelgraph-api","timestamp":"2025-08-15T08:33:43.615Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:08:33:45 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T08:33:45.350Z"}
{"level":"info","message":"Neo4j connection closed","service":"intelgraph-api","timestamp":"2025-08-15T08:33:53.792Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T08:33:53.793Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T14:21:45.710Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T14:21:45.737Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:14:21:49 +0000] \"GET /health HTTP/1.1\" 200 93 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T14:21:49.822Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:24:19.988Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T17:24:20.006Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:17:24:23 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T17:24:23.667Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:25:20.498Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T17:25:20.514Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:17:25:24 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T17:25:24.144Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:26:18.694Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T17:26:18.714Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:17:26:22 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T17:26:22.335Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T17:26:22.928Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:27:29.286Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T17:27:29.300Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T17:27:29.843Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:17:27:33 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T17:27:33.003Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:28:41.760Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T17:28:41.790Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T17:28:41.889Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:17:28:45 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T17:28:45.647Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T17:29:34.784Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T18:02:31.383Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T18:02:31.400Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T18:02:31.492Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:18:02:34 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T18:02:34.986Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T18:30:32.544Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T18:30:32.561Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T18:30:32.682Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:18:30:36 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T18:30:36.404Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T19:43:12.279Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T19:43:12.299Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T19:43:12.393Z"}
{"level":"error","message":"Error registering user: User with this email or username already exists","service":"intelgraph-api","stack":"Error: User with this email or username already exists\n    at AuthService.register (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:59:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:86:22)","timestamp":"2025-08-15T19:43:12.836Z"}
{"level":"error","message":"Error registering user: Cannot read properties of undefined (reading 'rows')","service":"intelgraph-api","stack":"TypeError: Cannot read properties of undefined (reading 'rows')\n    at AuthService.rows [as register] (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:58:24)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:100:7)","timestamp":"2025-08-15T19:43:12.840Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:107:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:128:7)","timestamp":"2025-08-15T19:43:12.843Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:114:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:135:7)","timestamp":"2025-08-15T19:43:12.844Z"}
{"level":"warn","message":"Invalid token:","service":"intelgraph-api","timestamp":"2025-08-15T19:43:12.845Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:19:43:16 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T19:43:16.352Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T19:44:24.178Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T19:44:24.193Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T19:44:24.301Z"}
{"level":"error","message":"Error registering user: User with this email or username already exists","service":"intelgraph-api","stack":"Error: User with this email or username already exists\n    at AuthService.register (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:59:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:90:22)","timestamp":"2025-08-15T19:44:24.651Z"}
{"level":"error","message":"Error registering user: Cannot read properties of undefined (reading 'length')","service":"intelgraph-api","stack":"TypeError: Cannot read properties of undefined (reading 'length')\n    at AuthService.length [as register] (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:58:29)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:105:7)","timestamp":"2025-08-15T19:44:24.653Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:107:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:134:7)","timestamp":"2025-08-15T19:44:24.655Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:114:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:141:7)","timestamp":"2025-08-15T19:44:24.655Z"}
{"level":"warn","message":"Invalid token:","service":"intelgraph-api","timestamp":"2025-08-15T19:44:24.656Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:19:44:27 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T19:44:27.901Z"}
{"code":"ECONNREFUSED","level":"error","message":"‚ùå Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T19:45:34.039Z"}
{"level":"info","message":"PostgreSQL connection closed","service":"intelgraph-api","timestamp":"2025-08-15T19:45:34.059Z"}
{"level":"warn","message":"Redis client not available","service":"intelgraph-api","timestamp":"2025-08-15T19:45:34.159Z"}
{"level":"error","message":"Error registering user: User with this email or username already exists","service":"intelgraph-api","stack":"Error: User with this email or username already exists\n    at AuthService.register (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:59:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:107:7)","timestamp":"2025-08-15T19:45:34.565Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:107:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:136:7)","timestamp":"2025-08-15T19:45:34.570Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:114:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:143:7)","timestamp":"2025-08-15T19:45:34.571Z"}
{"level":"warn","message":"Invalid token:","service":"intelgraph-api","timestamp":"2025-08-15T19:45:34.572Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [15/Aug/2025:19:45:37 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-15T19:45:37.926Z"}
{"level":"info","message":"::ffff:127.0.0.1 - - [16/Aug/2025:01:40:37 +0000] \"GET /health HTTP/1.1\" 200 100 \"-\" \"-\"","service":"intelgraph-api","timestamp":"2025-08-16T01:40:37.346Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:00:20.099Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:00:20.102Z"}
{"level":"info","message":"‚úÖ Redis ready","service":"intelgraph-api","timestamp":"2025-09-02T19:00:20.105Z"}
{"level":"info","message":"‚úÖ Connected to Redis","service":"intelgraph-api","timestamp":"2025-09-02T19:00:20.106Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:00:20.112Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:00:32.771Z"}
{"level":"info","message":"‚úÖ Redis ready","service":"intelgraph-api","timestamp":"2025-09-02T19:00:32.776Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:00:32.777Z"}
{"level":"info","message":"‚úÖ Connected to Redis","service":"intelgraph-api","timestamp":"2025-09-02T19:00:32.780Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:00:32.784Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:31:31.419Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:31:31.421Z"}
{"level":"info","message":"‚úÖ Redis ready","service":"intelgraph-api","timestamp":"2025-09-02T19:31:31.442Z"}
{"level":"info","message":"‚úÖ Connected to Redis","service":"intelgraph-api","timestamp":"2025-09-02T19:31:31.444Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:31:31.449Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:31:48.497Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:31:48.502Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:31:48.504Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:31:48.505Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:31:48.505Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:31:48.505Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:31:48.508Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:31:54.072Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:31:54.078Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:31:54.079Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:31:54.081Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:31:54.081Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:31:54.081Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:31:54.085Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:32:02.796Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:32:02.801Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:32:02.801Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:32:02.806Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:32:02.806Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:32:02.806Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:32:02.809Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:32:17.580Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:32:17.583Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:32:17.586Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:32:17.588Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:32:17.588Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:32:17.588Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:32:17.590Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:32:49.543Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:32:49.544Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:32:49.545Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:32:49.547Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:32:49.547Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:32:49.547Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:32:49.549Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:34:47.391Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:34:47.400Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:34:47.400Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:34:47.403Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:34:47.404Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:34:47.404Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:34:47.406Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:34:57.793Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:34:57.797Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:34:57.798Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:34:57.804Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:34:57.804Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:34:57.804Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:34:57.809Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:35:41.407Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:35:41.410Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:35:41.413Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:35:41.417Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:35:41.417Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:35:41.417Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:35:41.419Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:35:50.696Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:35:50.705Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:35:50.705Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:35:50.708Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:35:50.708Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:35:50.708Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:35:50.710Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:36:10.667Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:36:10.669Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:36:10.670Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:36:10.677Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:36:10.677Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:36:10.677Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:36:10.682Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:36:17.548Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:36:17.556Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:36:17.557Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:36:17.560Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:36:17.560Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:36:17.560Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:36:17.564Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:36:27.378Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:36:27.380Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:36:27.381Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:36:27.383Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:36:27.383Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:36:27.383Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:36:27.385Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:40:49.230Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:40:49.233Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:40:49.233Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:40:49.236Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:40:49.236Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:40:49.237Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:40:49.239Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:41:13.244Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:41:13.246Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:41:13.246Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:41:13.248Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:41:13.248Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:41:13.248Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:41:13.250Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:41:48.952Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:41:48.953Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:41:48.953Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:41:48.955Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:41:48.955Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:41:48.955Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:41:48.960Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:41:49.007Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:41:49.842Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:41:49.848Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.622Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:42:14.624Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.625Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.627Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.627Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.627Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:42:14.632Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.678Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.681Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.682Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.791Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.795Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:42:14.800Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.525Z"}
{"classification":"UNKNOWN","code":"ServiceUnavailable","diagnosticRecord":{"CURRENT_SCHEMA":"/","OPERATION":"","OPERATION_CODE":"0"},"gqlStatus":"50N42","gqlStatusDescription":"error: general processing exception - unexpected error. Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","level":"error","message":"‚ùå Failed to connect to Neo4j: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.","name":"Neo4jError","retriable":true,"service":"intelgraph-api","stack":"Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.\n\n    at captureStacktrace (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:624:17)\n    at new Result (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/result.js:112:23)\n    at Session._run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:224:16)\n    at Session.run (/Users/brianlong/Documents/GitHub/intelgraph/node_modules/neo4j-driver-core/lib/session.js:188:27)\n    at connectNeo4j (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:21:19)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:26:7)","timestamp":"2025-09-02T19:42:24.533Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.533Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.535Z"}
{"level":"error","message":"‚ùå Failed to connect to Redis:","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.535Z"}
{"level":"warn","message":"Server will continue without Redis caching","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.535Z"}
{"code":"28P01","file":"auth.c","length":106,"level":"error","line":"331","message":"‚ùå Failed to connect to PostgreSQL: password authentication failed for user \"intelgraph\"","name":"error","routine":"auth_failed","service":"intelgraph-api","severity":"FATAL","stack":"error: password authentication failed for user \"intelgraph\"\n    at /Users/brianlong/Documents/GitHub/intelgraph/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.ts:119:20)\n    at async Promise.allSettled (index 1)\n    at async startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/src/index.ts:25:5)","timestamp":"2025-09-02T19:42:24.538Z"}
{"level":"info","message":"Redis connected","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.597Z"}
{"level":"error","message":"Redis error:","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.602Z"}
{"level":"info","message":"Redis reconnecting...","service":"intelgraph-api","timestamp":"2025-09-02T19:42:24.604Z"}
