{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:23.805Z"}
{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:26.860Z"}
{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:29.966Z"}
{"code":"ECONNRESET","errno":-54,"level":"error","message":"Redis error: read ECONNRESET","service":"intelgraph-api","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-08-14T01:41:33.123Z"}
{"level":"error","message":"Redis error: Command timed out","service":"intelgraph-api","stack":"Error: Command timed out\n    at Timeout._onTimeout (/Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/ioredis/built/Command.js:192:33)\n    at listOnTimeout (node:internal/timers:608:17)\n    at process.processTimers (node:internal/timers:543:7)","timestamp":"2025-08-14T01:47:36.956Z"}
{"level":"error","message":"Failed to start server: Router.use() requires a middleware function Router.use() requires a middleware function","service":"intelgraph-api","stack":"TypeError: Router.use() requires a middleware function\n    at router.use (/Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/express/lib/router/index.js:462:11)\n    at initializeRoutes (/Users/brianlong/Documents/GitHub/intelgraph/server/src/routes/warRoomRoutes.js:97:10)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/server.js:371:27)\n    at runNextTicks (node:internal/process/task_queues:65:5)\n    at listOnTimeout (node:internal/timers:569:9)\n    at process.processTimers (node:internal/timers:543:7)","timestamp":"2025-08-14T01:49:16.586Z"}
{"address":"::","code":"EADDRINUSE","errno":-48,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::4000 listen EADDRINUSE: address already in use :::4000","port":4000,"service":"intelgraph-api","stack":"Error: listen EADDRINUSE: address already in use :::4000\n    at Server.setupListenHandle [as _listen2] (node:net:1940:16)\n    at listenInCluster (node:net:1997:12)\n    at Server.listen (node:net:2102:7)\n    at startServer (/Users/brianlong/Documents/GitHub/intelgraph/server/server.js:446:16)\n    at runNextTicks (node:internal/process/task_queues:65:5)\n    at listOnTimeout (node:internal/timers:569:9)\n    at process.processTimers (node:internal/timers:543:7)","syscall":"listen","timestamp":"2025-08-14T01:51:14.832Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Redis error: connect ECONNREFUSED 127.0.0.1:6379","port":6379,"service":"intelgraph-api","stack":"Error: connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)","syscall":"connect","timestamp":"2025-08-14T01:51:41.074Z"}
{"code":"EPIPE","errno":-32,"level":"error","message":"Uncaught Exception: write EPIPE write EPIPE","service":"intelgraph-api","stack":"Error: write EPIPE\n    at afterWriteDispatched (node:internal/stream_base_commons:159:15)\n    at writeGeneric (node:internal/stream_base_commons:150:3)\n    at Socket._writeGeneric (node:net:966:11)\n    at Socket._write (node:net:978:8)\n    at writeOrBuffer (node:internal/streams/writable:570:12)\n    at _write (node:internal/streams/writable:499:10)\n    at Writable.write (node:internal/streams/writable:508:10)\n    at Console.log (/Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/winston/lib/winston/transports/console.js:87:23)\n    at Console._write (/Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/winston-transport/modern.js:103:17)\n    at doWrite (/Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/readable-stream/lib/_stream_writable.js:390:139)","syscall":"write","timestamp":"2025-08-14T02:38:46.806Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T15:56:12.539Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.558Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.559Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.564Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:24:36.567Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:25:36.528Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:27:28.436Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:27:28.524Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:27:28.604Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:28:51.693Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:28:51.799Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:30:13.757Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-14T19:30:13.844Z"}
{"level":"error","message":"❌ Migration 001_initial_entity_model failed:","service":"intelgraph-api","timestamp":"2025-08-15T08:29:34.102Z"}
{"level":"error","message":"❌ Migration 001_initial_entity_model failed:","service":"intelgraph-api","timestamp":"2025-08-15T08:33:43.363Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T14:21:45.710Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:24:19.988Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:25:20.498Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:26:18.694Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:27:29.286Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T17:28:41.760Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T18:02:31.383Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T18:30:32.544Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T19:43:12.279Z"}
{"level":"error","message":"Error registering user: User with this email or username already exists","service":"intelgraph-api","stack":"Error: User with this email or username already exists\n    at AuthService.register (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:59:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:86:22)","timestamp":"2025-08-15T19:43:12.836Z"}
{"level":"error","message":"Error registering user: Cannot read properties of undefined (reading 'rows')","service":"intelgraph-api","stack":"TypeError: Cannot read properties of undefined (reading 'rows')\n    at AuthService.rows [as register] (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:58:24)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:100:7)","timestamp":"2025-08-15T19:43:12.840Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:107:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:128:7)","timestamp":"2025-08-15T19:43:12.843Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:114:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:135:7)","timestamp":"2025-08-15T19:43:12.844Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T19:44:24.178Z"}
{"level":"error","message":"Error registering user: User with this email or username already exists","service":"intelgraph-api","stack":"Error: User with this email or username already exists\n    at AuthService.register (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:59:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:90:22)","timestamp":"2025-08-15T19:44:24.651Z"}
{"level":"error","message":"Error registering user: Cannot read properties of undefined (reading 'length')","service":"intelgraph-api","stack":"TypeError: Cannot read properties of undefined (reading 'length')\n    at AuthService.length [as register] (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:58:29)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:105:7)","timestamp":"2025-08-15T19:44:24.653Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:107:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:134:7)","timestamp":"2025-08-15T19:44:24.655Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:114:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:141:7)","timestamp":"2025-08-15T19:44:24.655Z"}
{"code":"ECONNREFUSED","level":"error","message":"❌ Failed to connect to PostgreSQL:","service":"intelgraph-api","stack":"AggregateError: \n    at /Users/brianlong/Documents/GitHub/intelgraph/server/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at connectPostgres (/Users/brianlong/Documents/GitHub/intelgraph/server/src/config/database.js:112:20)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/src/tests/entityModel.test.js:13:5)","timestamp":"2025-08-15T19:45:34.039Z"}
{"level":"error","message":"Error registering user: User with this email or username already exists","service":"intelgraph-api","stack":"Error: User with this email or username already exists\n    at AuthService.register (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:59:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:107:7)","timestamp":"2025-08-15T19:45:34.565Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:107:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:136:7)","timestamp":"2025-08-15T19:45:34.570Z"}
{"level":"error","message":"Error logging in user: Invalid credentials","service":"intelgraph-api","stack":"Error: Invalid credentials\n    at AuthService.login (/Users/brianlong/Documents/GitHub/intelgraph/server/src/services/AuthService.js:114:15)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at Object.<anonymous> (/Users/brianlong/Documents/GitHub/intelgraph/server/tests/services/AuthService.test.js:143:7)","timestamp":"2025-08-15T19:45:34.571Z"}
